[build]
  command = "node node_modules/vite/bin/vite.js build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://bind-node-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
